version: '3.7'

services:
  portainer:
    restart: always
    image: whatwewant/connect-doreamon:v1
    environment:
      CLIENT_ID: ${SERVICE_PORTAINER_CLIENT_ID}
      CLIENT_SECRET: ${SERVICE_PORTAINER_CLIENT_SECRET}
      REDIRECT_URI: ${SERVICE_PORTAINER_REDIRECT_URI}
      UPSTREAM: portainer_upstream:9000

  portainer_upstream:
    restart: always
    image: whatwewant/portainer:${SERVICE_PORTAINER_VERSION}
    volumes:
      - ${SERVICE_DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: compose-ingress
