version: '3.7'

services:
  portainer:
    restart: always
    image: whatwewant/openresty-oauth2.0:${SERVICE_PORTAINER_OAUTH_VERSION}
    environment:
      PROXY_PASS: http://portainer-server:9000
      ROOT_URL: https://${SERVICE_PORTAINER_DOMAIN}
      PROVIDER: doreamon
      CLIENT_ID: ${SERVICE_PORTAINER_DOREAMON_CLIENT_ID}
      CLIENT_SECRET: ${SERVICE_PORTAINER_DOREAMON_CLIENT_SECRET}
      ALLOW_USERNAMES: ${SERVICE_PORTAINER_ALLOW_USERNAMES}

  portainer-server:
    restart: always
    image: whatwewant/portainer:${SERVICE_PORTAINER_VERSION}
    volumes:
      - ${SERVICE_DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external: true
    name: compose-ingress
